remote_theme: dracula/gh-pages
plugins:
- jekyll-remote-theme

title: [Tutorial on Flutter Sort List]
description: [Sort a List by at least 2 different fields with both ascending and descending option]
icon: [assets/icon.png]
